apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: default
  labels:
    app: todo-backend
    component: backend
data:
  PORT: "8080"
  GIN_MODE: "release"
  CORS_ALLOWED_ORIGINS: "*"
  API_VERSION: "v1"